version: "3.7"
services:
  db:
    image: mysql:8.0
    container_name: abc-article-network-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - abc-article-network

  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: abc-article
    container_name: abc-article
    restart: unless-stopped
    working_dir: /app
    env_file:
    - .env
    ports:
      - "8000:8181"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - abc-article-network

networks:
  abc-article-network:
    driver: bridge